version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagelite
    ports:
      - '5432:5432'
    networks:
      - certificadonetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - certificadonetwork

  sbootapp:
    build:
      dockerfile: Dockerfile
      context: ./gerenciador-certificado-api
    container_name: certificadoapi
    restart: on-failure
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - certificadonetwork
    environment:
      - "POSTGRES_HOST=db"
      - "POSTGRES_PORT=5432"
      - "SECURITY_PASSWORD=password"

  frontapp:
    build:
      dockerfile: Dockerfile
      context: ./gerenciador-certificado-ui
    container_name: certificadoapp
    restart: on-failure
    depends_on:
      - sbootapp
    ports:
      - '3000:3000'
    networks:
      - certificadonetwork
    expose:
      - 3000

networks:
  certificadonetwork:
    driver: bridge
