version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: certificate_manage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Info@1234
    ports:
      - "2222:5432"
    volumes:
      - ./data:/var/lib/postgresql/data